# Generated by Django 3.1.5 on 2021-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
