# Generated by Django 3.1.7 on 2021-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_cancerdisease_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.FloatField()),
                ('Glucose', models.FloatField()),
                ('BloodPressure', models.FloatField()),
                ('SkinThickness', models.FloatField()),
                ('Insulin', models.FloatField()),
                ('BMI', models.FloatField()),
                ('DiabetesPedigreeFunction', models.FloatField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
