# Generated by Django 3.1.7 on 2021-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_diabetesdisease_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThroatTumorDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri', models.ImageField(upload_to='')),
                ('prediction', models.ImageField(upload_to='')),
            ],
        ),
    ]
