# Generated by Django 3.1.7 on 2021-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_throattumordisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='throattumordisease',
            name='title',
            field=models.CharField(default='ThroatTumorMRI', max_length=100),
        ),
        migrations.AlterField(
            model_name='throattumordisease',
            name='mri',
            field=models.ImageField(upload_to='throat_mri'),
        ),
        migrations.AlterField(
            model_name='throattumordisease',
            name='prediction',
            field=models.ImageField(upload_to='throat_prediction'),
        ),
    ]
