# Generated by Django 3.1.7 on 2021-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20210305_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throattumordisease',
            name='prediction',
            field=models.ImageField(null=True, upload_to='throat_prediction'),
        ),
    ]
