# Generated by Django 3.1.5 on 2021-03-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20210306_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throattumordisease',
            name='prediction',
            field=models.JSONField(null=True),
        ),
    ]
