# Generated by Django 3.1.5 on 2021-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20210324_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throattumordisease',
            name='mri',
            field=models.ImageField(upload_to='mri_images'),
        ),
    ]
