# Generated by Django 3.1.5 on 2021-03-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20210324_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throattumordisease',
            name='mri',
        ),
    ]
