# Generated by Django 3.1.5 on 2021-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_remove_throattumordisease_mri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throattumordisease',
            name='title',
            field=models.CharField(default='ThroatTumorMRI', max_length=1000),
        ),
    ]
